### ISSUE TITLE
Draft Pre-Training Assessment

### ISSUE THREAD

**Issue by shapaklyak** [ICPI/tableau_training#1]
Create a pre-training survey for participants, including the following assessment

- Comfort level and usage of Tableau use (importing dataset, creating visuals, etc.)
- Expectations upon completion of training
- Current issues encountered in using Tableau
- ...

**Comment by shapaklyak** [comment]
Send out by March 26, Due back from participants by April 6.

**Comment by shapaklyak** [comment]
For review @ICPI/guidance-capacity-building meeting 3/20

[ICPI Tableau Pre-Training Assessment_20180319v1_BB EN.docx](https://github.com/ICPI/tableau_training/files/1826592/ICPI.Tableau.Pre-Training.Assessment_20180319v1_BB.EN.docx)

**Comment by achafetz** [comment]
:thumbsup: looks good to me.

I think question 3 may be a throw away question though - "3. Are you responsible for analyzing and/or visualizing data in your position?" Hard to imagine anyone responding no.

Another question or series of questions may be to see if they have familiarity withother types of visualization or analytic software to help gauge "preparedness"

**Comment by shapaklyak** [comment]
Good point @achafetz regarding throw-away q and other software. I removed q3 and instead added this one...any other software you would add? 

![image](https://user-images.githubusercontent.com/5234106/37619927-d20eea1e-2b88-11e8-864a-0fb1376b9333.png)

**Comment by achafetz** [comment]
ArcGIS/QGIS

**Comment by shapaklyak** [comment]
Updated survey, please review @bbaack @achafetz @noahbartlett @kschlenker 
https://www.surveymonkey.com/r/6XBH7NV 

question limit for free version that ICPI uses is 10q's. so i took out the Tableau server question and consolidate a couple.

**Comment by shapaklyak** [comment]
also - do we want to put the registration and pre-training assessment into one survey? So collect names/emails within the pre-training assessment. could then replace q1 with name/email instead of what agency do you work for and have one link for registration and assessment.

**Comment by noahbartlett** [comment]
Revise question #6 to specify Tableau Desktop.

**Comment by bbaack** [comment]
@shapaklyak sorry for the delayed response. If we are attempting to consolidate questions, I think 4 & 5 could be combined (but don't frequently use survey monkey, so not sure...). Something like: Which version of Tableau do you currently have installed on your computer? A. Tableau Desktop; B: Tableau Reader; C. Both; D: Neither, with specify the version number option for A-C. Question 6 would be contingent on answering B/D to the above. 

Question 7-- it might be clearer to just say "How comfortable (familiar?) are you with using Tableau?"

Agree with removing Q1 and replacing with name/email. 

Thanks again for putting this together!

**Comment by shapaklyak** [comment]
thanks all for the edits. i've revised Q1 & Q2 to the following, and Q7 to "how comfortable...." 
https://www.surveymonkey.com/r/6XBH7NV 
are you all good with this being sent out this week, with a registration close date of April 30? @achafetz @bbaack @kschlenker @noahbartlett 

![image](https://user-images.githubusercontent.com/5234106/38582171-ed5fc350-3cdc-11e8-8a63-151482b9b904.png)

**Comment by shapaklyak** [comment]
moved the [training registration & assessment](https://docs.google.com/forms/d/e/1FAIpQLSfY1EK0RIezcj6L1mDllSRZ6ClJqJtQ5TIXSjM39CrSGjqi-g/viewform) to google forms with ICPI account. now we won't have any issues exporting data. 
**final review by COB 4/19**

**Comment by achafetz** [comment]
Asking as someone who doesn't know much about Tableau, is there importance around knowing which of the 6 version of Tableau and Tableau reader the user has?

Is it worth asking which agency?

And then one minor note, "Javascript D3" should have a slash between them, "Javscript/d3".

Otherwise, looks good!

**Comment by shapaklyak** [comment]
thanks @achafetz ! For knowing which version of Tableau they have, we can plan for the version to save Tableau files for the training materials. If you save a Tableau file with a higher version, and I only have a lower version on my computer, then I can't open it unless I run this [converter](http://www.dataplusscience.com/ConvertTableau.html). Tableau Reader...I guess we really don't need to know but it would help that users have the latest version. I can add agency, too. Thanks for the d3 correction!

**Comment by shapaklyak** [comment]
assessment sent out and compiling results
