### ISSUE TITLE
June 11 Email Reminder + Pre-work

### ISSUE THREAD

**Issue by shapaklyak** [ICPI/tableau_training#11]
@bbaack @kschlenker @hessionra please review

fyi @jb3436 

To: Registered participants
CC: ICPI Leads, ICPI Coordinator,

Hello everyone,

We are excited to have you as part of the ICPI Tableau Training on June 21st. To get the most out of the training and be prepared to jump right in, please complete the two tasks below. This should take at most 1 hour of your time. 

1. [Getting Started with Tableau video](https://www.tableau.com/learn/tutorials/on-demand/getting-started?product=tableau_desktop&version=10_0&topic=getting_started) (20min)
2. Build a basic bar graph using a public dataset ([instructions & public dataset](https://github.com/ICPI/tableau_training/tree/master/Pre-Work))

We will hold office hours on Thursday 6/14 (1:30-2:30pm) and Tuesday 6/19 (3-4pm) for anyone that would like to ask questions or work together on the above tasks. Look out for calendar invites in your inboxes shortly.

Logistics prep: Please make sure you can open Tableau Desktop on the laptop you will be using when you attend the training. If you plan to use a trial version of Tableau Desktop, please make sure that this will not expire before the June 21st training. If you do not have Tableau Desktop and won't have it in time for the training, please let us know by June 18th so we can procure loaner laptops. This training will be most beneficial in person, however if you choose to dial-in or connect via adobe, please note that we do not have the capacity to provide assistance during the hands-on portion on June 21st. 

Thank you,

**Comment by hessionra** [comment]
This looks great Katya! I would put that the office hours will be held in North America.

Also, will we need multiple wifis for this training, given the number of participants?

**Comment by shapaklyak** [comment]
@hessionra thanks! Yes, we will need wifis for this training. Thank you! 

I reserved North America room, but perhaps on Monday after this email goes out, we can send out calendar invites with adobe/phone line for the office hours? 

I also, saved instructions for the task on [pepfar.net ](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FTrainings%2FICPI%20Tableau%20Training%20June%202018%2FPre%2Dwork&FolderCTID=0x01200080CC6F83D1766F4D9E3497D4529EC74A&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D) if you want to send out the instructions (only) with the email.

**Comment by shapaklyak** [comment]
Any comments on the email or pre-work? @bbaack @kschlenker  I'd like to get this sent out COB today or first thing Tuesday morning.

**Comment by bbaack** [comment]
@shapaklyak Email looks great! Pre-training slides look great, too. My only suggestion is that we go ahead and download and share the file from the public dashboards with the email, then start the slides from there. Also, I wasn't able to open the helper file, but might just be an issue with my computer. Can we get someone else to check?

**Comment by shapaklyak** [comment]
@bbaack thanks for reviewing. I'll have others check the helper file..but it could be the Tableau version needed to be switched (instructions at end of powerpoint). 

@hessionra can you please send the above message with the links out to the specified individuals? let me know if any q's. thanks!

**Comment by bbaack** [comment]
@shapaklyak oh yep, duh. i bet that's the problem.

**Comment by hessionra** [comment]
Email sent to registrants and ICPI leads on 6/12!

**Comment by shapaklyak** [comment]
thanks @hessionra ! did you happen to cc me on it? :)
