### ISSUE TITLE
June 18 Email Reminder

### ISSUE THREAD

**Issue by shapaklyak** [ICPI/tableau_training#12]
To: Registered participants
CC: ICPI Leads, ICPI Coordinator,

Hello everyone,

We are excited to have you as part of the ICPI Tableau Training this week on June 21st!

Few tasks to help you make the most of the training on Thursday: 

1. [Getting Started with Tableau video ](https://www.tableau.com/learn/tutorials/on-demand/getting-started?product=tableau_desktop&version=10_0&topic=getting_started)(20min)
2. Build a basic bar graph using a public dataset ([instructions](https://github.com/ICPI/tableau_training/tree/master/Pre-Work))

We will hold office hours this Tuesday 6/19 (3-4pm) for anyone that would like to ask questions or work together on the above tasks. 

Logistics prep: Please make sure you can open Tableau Desktop on the laptop you will be using when you attend the training. If you plan to use a trial version of Tableau Desktop, please make sure that this will not expire before the June 21st training. If you do not have Tableau Desktop and won't have it in time for the training, please let us know **by June 18th** so we can procure loaner laptops. This training will be most beneficial in person, however if you choose to dial-in or connect via adobe, please note that we do not have the capacity to provide assistance during the hands-on portion on June 21st.

Logistics: @hessionra to add additional details on entry to building in Outlook

Thank you,

**Comment by shapaklyak** [comment]
@bbaack @jb3436 anything else to add to this message before it is sent out on Monday (after inbrief)? 

@hessionra there are 2 additional participants, please use this list and include all DC-based ICPI analysts, and cc ICPI Leads. 
[Registered Attendees20180615.xlsx](https://github.com/ICPI/tableau_training/files/2106969/Registered.Attendees20180615.xlsx)

**Comment by hessionra** [comment]
Sent 6/18 at 2:45pm.

**Comment by shapaklyak** [comment]
thank you!
