### ISSUE TITLE
Tableau office hours calendar invites (6/14 & 6/19)

### ISSUE THREAD

**Issue by shapaklyak** [ICPI/tableau_training#17]
@hessionra please include an adobe connect & phone# we could use. I've already reserved North America room for the below times. Can you please send this out **Tuesday, 6/11 @ 10am?** 

TO: Registered participants + ICPI DC-based analysts
[Registered Attendees20180531.xlsx](https://github.com/ICPI/tableau_training/files/2091528/Registered.Attendees20180531.xlsx)

CC: ICPI Leads, ICPI Coordinator

--------------
Dear Tableau training participants, 

DIV will hold office hours on Thursday 6/14 (1:30-2:30pm) and Tuesday 6/19 (3-4pm) for anyone that would like to ask questions or work together on the Tableau training pre-work assignment.

**Comment by shapaklyak** [comment]
@hessionra ready to send out. thanks!

**Comment by hessionra** [comment]
Emailed out 6/12!
