### ISSUE TITLE
Identify 3-5 Tableau facilitators

### ISSUE THREAD

**Issue by shapaklyak** [ICPI/tableau_training#19]
To walk around the room and make sure participants are on the same page and following. Please add yourself as an assignee if you can support as a facilitator.
FYI @jb3436 @bbaack

**Comment by kschlenker** [comment]
Greg Rosen from USAID is also able to act as a facilitator (not sure if he's on github though)

**Comment by shapaklyak** [comment]
thanks @kschlenker and Greg! We'll be holding a call on Tuesday at 4pm to review materials and facilitator needs. You may find the [current training materials](https://github.com/ICPI/tableau_training/tree/master/Training%20materials) and [training outline](https://github.com/ICPI/tableau_training/blob/master/Planning/ICPI%20Tableau%20Training%20Outline.docx).

**Comment by shapaklyak** [comment]
Please join the Slack group for Tableau users. This is where facilitators can help triage those attending virtually. 

https://join.slack.com/t/icpi-pepfar/shared_invite/enQtMzgzNjcxMzQ2ODg1LTQ0OTE4NWUwMzIwOGM3Y2ZmNGU1YmExYzkyMjdkMzNmOTE1NTg5ZTJlY2M1YTJjMmVmNGQ5MDFhMGRlMmMxMDE
