### ISSUE TITLE
Examples of other PEPFAR tableau workbooks

### ISSUE THREAD

**Issue by kschlenker** [ICPI/tableau_training#21]
@shapaklyak @bbaack I've posted [two tableau workbooks](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FClusters%2FDIV%2FWorking%20Folder%2FTableau%20examples&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D) from USAID. First, there is a Male Testing site level tool that I created. The second is a KP tool that Greg created. Both of us will be able to assist as facilitators and we're  happy to demo the tool or answer questions about it during the training - though these are both from Q4

**Comment by shapaklyak** [comment]
@kschlenker I'm not able to open the workbooks...it seems they were created in a version higher than 10.4. Are you able to save it in 10.0 by any chance? If not, could you export it as a PDF at least so folks can see what it looks like in the interim? 

Please save here: https://github.com/ICPI/tableau_training/tree/master/Additional%20Resources 
and on [sharepoint](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FTrainings%2FICPI%20Tableau%20Training%20June%202018%2FAdditional%20Resources%2FTableau%20examples&FolderCTID=0x01200080CC6F83D1766F4D9E3497D4529EC74A&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D ) 

thank you!

**Comment by kschlenker** [comment]
I'm not able to down-version them now and I can't post screenshots of the tool on github because it's sensitive data, but I've uploaded a word doc with views of the finding men tool on sharepoint.

**Comment by shapaklyak** [comment]
@kschlenker Thanks!!
