### ISSUE TITLE
Update Calendar Invite at 4pm today 

### ISSUE THREAD

**Issue by shapaklyak** [ICPI/tableau_training#24]
fyi @jb3436 @bbaack, anything else?
@hessionra , will email you the slack invite link & training materials link by 4pm.

- add adobe connect link
- add phone number
- add slack invite link (will send you link)
- download training materials link (github/sharepoint)

**Comment by hessionra** [comment]
Done! 6/20, 4:25pm.

**Comment by shapaklyak** [comment]
thank you!!
